language: node_js
node_js:
- '4'
cache:
  directories:
  - node_modules

# Build docs using latest docpress plugins
script:
- npm install docpress && ./node_modules/.bin/docpress build

# Deploy to gh-pages
after_success:
- npm run coveralls
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi

env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: fincher@fincher.im
  - GITHUB_REPO: justinfincher/ProjectSkylineManual
  - GIT_SOURCE: _docpress